name: Test workflow

on:
  workflow_dispatch:
    
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test date
        run: date
      - name: Test directory files
        run: 
        |
          ls -l
          echo "Hola mundo" > hola.txt
          ls -l 
          cat hola.txt